# Puerto diferente para no chocar con ms-pets
server.port=8083
# Cambia 'mail.sendgrid.key' por 'sendgrid.api.key'
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=${SENDGRID_FROM_EMAIL}
sendgrid.template.id=d-6b4bbd3879f446128c10c7cad2373c81
# Permitir que las herramientas de OpenAPI expongan los datos sin restricciones
springdoc.api-docs.enabled=true