# Etapa 1: Construcción (Maven con Temurin 17)
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Etapa 2: Ejecución (Temurin 17 JRE - Jammy)
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

# Copiamos el jar generado
COPY --from=build /app/target/*.jar app.jar

# Puerto interno fijo para el BFF
EXPOSE 8080

# Comando de arranque respetando el puerto dinámico de Docker
ENTRYPOINT ["sh", "-c", "java -jar app.jar --server.port=${SERVER_PORT}"]